import { Inter, Montserrat } from "next/font/google";
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "My Profile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={montserrat.className}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
      
    </html>
  );
}
